export const projects = [
  {
    title: 'Petrol Station System',
    description: "A managment system for a petrol station , consist of both web app and mobile application .It can manage all the requirment for a petrol station(accounting-shipments-containers...)",
    image: '/images/Petrol.PNG',
    tags: ['Flutter', 'Firebase', 'PHP', 'MySQL', 'Ajax', 'JQuery'],
    source: 'https://google.com',
    visit: 'https://github.com/hbfawaz112/Petrol-Station',
    id: 0,
  },
  {
    title: 'FCSS Web Site',
    description: "FCSS small company in Tebnin, this project is a website for this business consist as a E-commerce site with addto cart, product detail , check out , a contact page and a store page.",

    image: '/images/fcss1.png',
    tags: ['ReactJS', 'Commerce.js', 'Material UI'],
    source: 'https://google.com',
    visit: 'https://github.com/hbfawaz112/FCSS-Site',
    id: 0,
  },
  {
    title: 'LFA Grassroots',
    description: "A system for the lebanese football association (grassroots)contain an admin site to manage (crud) all required data and a mobile app for users to see all these data(results/news/matches/rank).",
    image: '/images/LFA-Grassroots.PNG',
    tags: ['Flutter', 'PHP', 'MySQL', 'API'],
    source: 'https://google.com',
    visit: 'https://github.com/hbfawaz112/LFA-Grassroots',
    id: 0,
  },
  {
    title: 'Mushroom Detector',
    description: " An app used to detect and predict the type of the mushroom by taking a picture of it from a camera or import the image from the gallery. Plus some guide about many kinds of  mushrooms",
    image: '/images/mushrrom.png',
    tags: ['Flutter', 'Machine Learning ',' Tenserflow Lite'],
    source: 'https://google.com',
    visit: 'https://github.com/hbfawaz112/Mushroom-Detector-Flutter-ML',
    id: 0,
  },
  {
    title: ' Twitter Stream Data Analysis',
    description: " Stream data analysis pipline for the twitter sentiment analysis talking about a specif topic, using specific technologies and tools like kafka, azuer, mongodb and it was simulated in pyton",
    image: '/images/twitter_stream.PNG',
    tags: ['Python', 'Azure Cloud ', 'Kafka', 'MongoDB'],
    source: 'https://google.com',
    visit: 'https://github.com/hbfawaz112/Streaming-Data-Analysis',
    id: 0,
  },
  {
    title: 'Machine Learning And Data Science Projects',
    description: "Some Machine Learning and Data Science projects made with python such as Twitter Sentiment Analysis, Covid-19 Data Analysis, Face Detection, Image To Text, a bunch of ML algotithms and more.",
    image: '/images/ML_DS.png',
    tags: ['Data Science', 'ML','Image Recognition',' Python'],
    source: 'https://google.com',
    visit: 'https://github.com/hbfawaz112/ML-Data-Science-Projects',
    id: 0,
  },
  
  {
    title: 'UL-FS Form Of Discussion',
    description: "A website developed using ASP.NET MVC to let students communicate between them by asking public questions or private questions based on many factors , and reply to these questions",
    image: '/images/ulfs-forum.PNG',
    tags: ['ASP.NET-MVC ', ' Microsoft SQL Server  ', ' Bootstrap'],
    source: 'https://google.com',
    visit: 'https://github.com/hbfawaz112/UL-FS-Form-of-Discussion-ASP.NET-MVC',
    id: 1,
  },
  {
    title: 'Blogging Platform ',
    description: "A bloging platform site containing dynamic blog pages,have a dedicated editor for blogs, you can add/make as many blogs you want, you can add Headings,paragraphs,and images to the blog post.",
    image: '/images/blognode.png',
    tags: ['HTML/CSS', 'Node.js', ' Firebase Firestore'],
    source: 'https://google.com',
    visit: 'https://github.com/hbfawaz112/Blogging-Site-Full-Stack',
    id: 1,
  },

  {
    title: 'Moodle ULFS',
    description: "This is a web project developed using php-mysql , it’s about 2 website one for the instructors to upload files as pdf courses, sessions, … , and one for the students that can acces to their account and download these files.",
    image: '/images/moodle1.png',
    tags: ['PHP', 'MYSQL', 'Bootstrap'],
    source: 'https://google.com',
    visit: 'https://github.com/hbfawaz112/moodle-UL-Faculity-Of-Science',
    id: 1,
  },
  {
    title: 'Math Game Drag And Drop',
    description: "A Desktop game containing 3 sections,basic math(count objcets/comparaison),calculation section(Addition-Substraction-Multiplucation-Division-Random) and basic geometrie section, made for kids.",
    image: '/images/SS.png',
    tags: ['JavaFX - FXML - Controller'],
    source: 'https://google.com',
    visit: 'https://github.com/hbfawaz112/Javafx-MathGame-Drag-And-Drop',
    id: 1,
  },
  {
    title: 'Twitter Clone',
    description: "A social media site like twitter,containing authentication to create account and login , post a new tweet ,follow and unfollo users , like and comment tweests ,update your profile ....",
    image: '/images/twitter.png',
    tags: ['PHP', 'MongoDB', 'Bootstrap'],
    source: 'https://google.com',
    visit: 'https://github.com/hbfawaz112/Twitter-Clone',
    id: 1,
  },


  {
    title: 'Football Academies Managment System',
    description: "A Desktop app developed with java (GUI-swing) and Microsoft SQL Server for the databasr help managing data for  a football academy (Players , Coaches , Training and the academy balance and accounting)",
    image: '/images/fm.png',
    tags: ['javaSwing', 'Microsoft SQL Server'],
    source: 'https://google.com',
    visit: 'https://github.com/hbfawaz112/Football-Academies-Management-Systeme',
    id: 1,
  },


];

export const TimeLineData = [
  { year: 2017, text: 'Graduate From High School - GS', },
  { year: 2020, text: 'Graduate with BS In Computer Science From Lebanese University', },
  { year: 2021, text: 'Finishing My Master 1 In Computer Science, },
  { year: 2022, text: 'Continue My Master 2 In Data Science For Risk Analysis ', },
  { year: 2022, text: 'Started my internship in April as a software developer at Aphelio in Grenoble, France, },
  { year: 2023, text: 'Started my full-time job as Full Stack Developer at Aphelio in Grenoble, France},  
];
